#!/bin/bash

set -e

domain=$(sudo yunohost app setting oranjeproxy domain)
path=$(sudo yunohost app setting oranjeproxy path)

# Copy files to the right place
final_path=/var/www/oranjeproxy
sudo mkdir -p $final_path
sudo cp ../sources/index.php $final_path
sudo chown -R root:root $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/oranjeproxy.conf

# Make the app public
sudo yunohost app setting oranjeproxy skipped_uris -v "/"

# Reload Nginx and regenerate SSOwat conf
sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app ssowatconf
